TripTeller-repository/TripTeller_BE

package-lock.json, package.json, src/authentication/auth.controller.ts, src/authentication/auth.service.ts, src/dailyPlan/dailyPlan.controller.ts, src/dailyPlan/dailyPlan.service.ts, src/dailySchedule/dailySchedule.controller.ts, src/dailySchedule/dailySchedule.service.ts, src/expense/expense.service.ts, src/feed/feed.controller.ts, src/scrap/scrap.controller.ts, src/scrap/scrap.service.ts, src/travelLog/travelLog.service.ts, src/travelPlan/travelPlan.controller.ts, src/travelPlan/travelPlan.service.ts
수정사항
• 메소드명 수정 : 검토 후 한번 더 통일할 예정
• 메소드명 규칙
- 컨트롤러 메서드: getItems, putItem, patchItem, updateItem, deleteItem
- 서비스 메서드: findAllItems, findItemById, createNewItem, modifyItem, removeItem 등
버전 업데이트
"@nestjs/common": "^10.3.8",
=> 메소드명 수정 후 통일

src/app.controller.ts, src/app.service.ts
=> [PR#3] healthcheck API 추가

src/app.controller.ts, src/app.service.ts, src/scrap/scrap.service.ts, src/utils/feedExtractor.ts
=> [PR#4] 게시물 스크랩 여부 표시 추가

src/app.module.ts, src/feed/feed.controller.ts, src/feed/feed.service.ts, src/feed/feeds.controller.ts, src/feed/feeds.service.ts, src/utils/feedExtractor.ts
나의여행 페이지네이션, 스크랩여부 수정 
기간별조회는 제외
=> [PR#5] 나의여행 페이지네이션, 스크랩여부 (기간별조회 제외)

src/app.module.ts, src/feed/feeds.controller.ts, src/feed/feeds.service.ts, src/utils/feedExtractor.ts
우리의여행 페이지네이션, 스크랩여부 (기간별조회 제외)
=> [PR#6] 우리의여행 페이지네이션, 스크랩여부 (기간별조회 제외)

src/feed/feed.service.ts, src/feed/feeds.controller.ts, src/feed/feeds.service.ts, src/utils/feedExtractor.ts
우리의여행(feeds controller) 기간별조회 API 수정하였음.
기간별로 필터링 후 페이지네이션과 포맷팅을 해줘야 하는데,
페이지네이션과 포맷팅을 먼저 하는 바람에 적용하는 데서 문제가 있었음.
순서를 바꿔서 적용하니 해결됨.
=> [PR#8] 우리의여행 기간별조회 API 수정

src/feed/feed.controller.ts, src/feed/feed.service.ts, src/feed/feeds.service.ts
=> [PR#9]: 나의여행 게시물 기간별조회 API 수정

src/authentication/auth.service.ts, src/user/user.schema.ts
=> [PR#12] refresh 토큰 추가

src/authentication/auth.controller.ts, src/authentication/auth.service.ts, src/our-trip/our-trip.controller.ts, src/user/user.controller.ts, src/user/user.service.ts
닉네임 중복시 숫자 추가
ex. 입력한 닉네임 : 길동
이미 '길동'이 존재한다면 해당 회원의 닉네임은 '길동1'이 됨.
=> [PR#15][D] 닉네임 중복시 숫자 추가

src/search/search.controller.ts, src/search/search.module.ts, src/search/search.service.ts, src/travel-plan/region-name.enum.ts, src/travel-plan/travel-plan.schema.ts, src/utils/feed-extractor.ts
검색을 위한 Search 모듈 추가
- '내용' 검색 : 우리의여행 게시물 검색은 아직 완료 안 됨.
=> [PR#18][D] 검색을 위한 Search 모듈 추가

src/search/search.module.ts, src/search/search.service.ts
=> [PR#19][D] 검색 기능 추가

src/authentication/auth.controller.ts, src/main.ts, src/search/search.service.ts
=> [PR#20][D] 지역별 게시물 조회는 공개게시물만 가능

src/authentication/auth.controller.ts, src/authentication/auth.service.ts, src/main.ts
auth 서비스 메소드 수정
로그인 쪽에 불필요한 코드 제거
=> [PR#21][D] auth 서비스 메소드 수정

src/app.module.ts, src/authentication/auth.controller.ts, src/authentication/auth.middleware.ts, src/main.ts
**토큰이 있는 경우:**
1) 미들웨어는 헤더에서 토큰을 추출하고, 해당 토큰을 사용하여 사용자 ID와 oauth provider를 확인함.
2) 사용자 ID와 oauth provider 정보를 요청 객체(req)에 추가함.
3) 다음 미들웨어로 전달
**토큰이 없는 경우:**
어떤 작업도 수행하지 않고 다음 미들웨어로 전달
=> [PR#22][D] auth 미들웨어 로직 수정

src/authentication/auth.controller.ts, src/authentication/auth.guard.ts, src/daily-plan/daily-plan.controller.ts, src/daily-schedule/daily-schedule.controller.ts, src/my-trip/my-trip.controller.ts, src/our-trip/our-trip.controller.ts, src/scrap/scrap.controller.ts, src/travel-plan/travel-plan.controller.ts, src/user/user.controller.ts
로그인을 해야 이용 가능한 서비스 : auth 가드 등록
우리의여행 게시물 목록 중 본인이 스크랩한 게시물 표기를 위해 
미들웨어에서 받은 회원 정보 활용
=> [PR#22][D] auth 가드 생성

src/authentication/auth.middleware.ts, src/search/search.service.ts
=> [PR#23][D] 일부 서비스 로직 변경

src/app.module.ts, src/authentication/auth.controller.ts, src/authentication/auth.middleware.ts, src/authentication/auth.module.ts, src/authentication/auth.service.ts, src/daily-schedule/daily-schedule-index.service.ts, src/daily-schedule/daily-schedule.module.ts, src/daily-schedule/daily-schedule.schema.ts, src/feed/feed.module.ts, src/feed/feed.schema.ts, src/feed/feed.service.ts, src/main.ts, src/my-trip/my-trip.module.ts, src/our-trip/our-trip.module.ts, src/scrap/scrap.controller.ts, src/travel-plan/travel-plan-index.service.ts, src/travel-plan/travel-plan.controller.ts, src/travel-plan/travel-plan.module.ts, src/travel-plan/travel-plan.schema.ts
개발환경에서 쿠키 이슈 해결함
아직 배포환경은 설정하지 않음
=> [PR#24][D] 쿠키 이슈 해결

src/authentication/auth.controller.ts, src/authentication/auth.service.ts, src/authentication/dto/create-user.dto.ts, src/user/user.schema.ts
카카오로그인 구현 (쿠키 이슈 O)
프론트엔드와 로그인로직 맞춰보고 배포환경에서 되는지 확인해야 함.
백엔드 로그인로직 기본 구현은 완료함.
=> [PR#24][D] 카카오로그인 구현 (쿠키 이슈 O)

src/our-trip/our-trip.module.ts, src/our-trip/our-trip.service.ts, src/scrap/scrap.module.ts, src/utils/feed-extractor.ts
travelPlan._id로 다시 쿼리 후 불러와서 해결
=> 🐛 startDate, endDate 불러와지지 않는 오류 수정

src/utils/feed-extractor.ts
프론트엔드에서 데이터 불러올 때 오류난다고 해서 해결중
=> [PR#31][M] FeedExtractor 오류 수정

README.md
=> [PR#31][M] Readme 작성

README.md
- 일반 로그인 시퀀스 다이어그램 추가
- 카카오 로그인 시퀀스 다이어그램 추가
- 구현 내용 1개 추가 (class-validator)
=> [📝docs]: README ver.8
